service: aws-node-typescript-dynamodb
frameworkVersion: '2'

variablesResolutionMode: 20210219

custom:
  dotenvVars: ${file(./config/config.js)}

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.dotenvVars.NODE_ENV}
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        ${file(./config/serverless/db.iam.role.yaml)}

package:
  excludeDevDependencies: true
  individually: true

resources:
  Resources:
    ${file(./config/serverless/tables/dynamo.user.table.yaml)}

functions:
  api:
    handler: src/server.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline